### ISSUE TITLE
Makes W2G2 redundant?

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/files_lock#22]
Without trying a side by side comparison of functionality, this looks like an official locking app which means we should deprecate W2G2 as per https://github.com/newroco/W2G2/issues/55

**Comment by juliushaertl** [comment]
There is no reason or aim from my perspective to deprecate a community app. As it was already written in the linked issue open source is also about having the choice and apps may be different in terms of features and the way they work.

**Comment by putt1ck** [comment]
I agree open source can be about choice, but I also don't like wasted effort. If the official lock app can gain the features from W2G2 then I'd prefer to spend resource collaborating on this one rather than on maintaining W2G2
