### ISSUE TITLE
Missing capabilities no clue to find it

### ISSUE THREAD

**Issue by Aguay-val** [nextcloud/files_lock#235]
I'm using your apps and after several issues I came here to check if i could find new tips.

I saw that you suggest to check if the capabilities is "enable" through the API.

But when i do the request i don't see anything about "locks":

```
curl -L "http://admin:mysuperpowerpassword@server.fqdn.tld/ocs/v1.php/cloud/capabilities?format=json" \
        -H 'OCS-APIRequest: true'  | jq .
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 100,
      "message": "OK",
      "totalitems": "",
      "itemsperpage": ""
    },
    "data": {
      "version": {
        "major": 28,
        "minor": 0,
        "micro": 2,
        "string": "28.0.2",
        "edition": "",
        "extendedSupport": false
      },
      "capabilities": {
        "bruteforce": {
          "delay": 0,
          "allow-listed": false
        },
        "integration_openai": {
          "uses_openai": true
        },
        "theming": {
          "name": "Nextcloud",
          "url": "https://nextcloud.com",
          "slogan": "a safe home for all your data",
          "color": "#00679e",
          "color-text": "#ffffff",
          "color-element": "#00679e",
          "color-element-bright": "#00679e",
          "color-element-dark": "#00679e",
          "logo": "https://server.fqdn.tld/core/img/logo/logo.svg?v=0",
          "background": "#00679e",
          "background-plain": true,
          "background-default": true,
          "logoheader": "https://server.fqdn.tld/core/img/logo/logo.svg?v=0",
          "favicon": "https://server.fqdn.tld/core/img/logo/logo.svg?v=0"
        }
      }
    }
  }
}
```

Can you help me ?

**Comment by joshtrichards** [comment]
Do you actually have the *Temporary files lock* app installed?

**Comment by Aguay-val** [comment]
Yes i do : 
![image](https://github.com/nextcloud/files_lock/assets/2204373/44cc2c1f-7db3-4890-97cf-881c40e4fc19)

**Comment by joshtrichards** [comment]
Your capabilities output is missing *tons* of other entries that aren't related to *Temporary files lock*. Essentially every app should be listed there. You're even missing sections that can't be disabled in a Nextcloud installation (like `files`, which happens to be where the locking is reported).

So I think something else is going on in your environment.

I'm surprised you're not having other problems...

I suggest posting at the Help Forum - https://help.nextcloud.com - and including your system install method, active config (`occ config:list system`), etc.
