### ISSUE TITLE
uid is show on error messages instead of display name

### ISSUE THREAD

**Issue by small1** [nextcloud/files_lock#250]
When trying to open a locked file it shows uid in error message. See screenshot.

![uuid](https://github.com/nextcloud/files_lock/assets/317830/1aeb94c9-49a3-42a7-9930-9d6a91314a20)

https://github.com/nextcloud/files_lock/blob/545724d82a6cf3119f3de0aa4d9478bb8f65ed3a/lib/Controller/LockController.php#L153

That should probably have something with displayname instead.

**Comment by Mika-6-9** [comment]
Hi.
I no longer have the name in UID form displayed, but I have nothing displayed (we are in LDAP).
For me the subject is not closed.
Greetings.

![Capture d'écran 2024-03-28 111156](https://github.com/nextcloud/files_lock/assets/82665005/e8ba0a8c-dc63-4c25-ac03-088cbebe5ae6)
