### ISSUE TITLE
Issues with 3rdparty app daita / symfony / .. when apps have a private vendor directory.

### ISSUE THREAD

**Issue by noci2012** [nextcloud/files_lock#26]
This is the error show..
```
$ sudo -u www-data php occ files:lock 13 --status
PHP Fatal error:  Declaration of daita\MySmallPhpTools\Db\ExtendedQueryBuilder::exprLimitToDBFieldArray(string $field, array $values, bool $eq = true, bool $cs = true, string $alias = ''): OCP\DB\QueryBuilder\ICompositeExpression must be compatible with daita\MySmallPhpTools\IExtendedQueryBuilder::exprLimitToDBFieldArray(string $field, array $values, bool $cs = true, string $alias = ''): OCP\DB\QueryBuilder\ICompositeExpression in /data/WWW/nc.example.net/htdocs/apps/social/vendor/daita/my-small-php-tools/lib/Db/ExtendedQueryBuilder.php on line 49
```

installing files_lock seems to cause other tools to fail.  seemingly tools that have a private vendor library that is not exactly equal to the nextcloud 3rdprty supplied one.
(news is another with this issue, then it is about symfony)... 
It is the files_lock item that runs into trouble though.

**Comment by daita** [comment]
conflict with `social`, I will release a new version of the social app within next few weeks, busy on other tasks right now. 

you could try to copy the files from apps/files_lock/vendor/daita/ into apps/social/vendor/daita/ in a temporary fix.

**Comment by noci2012** [comment]
Thnx.
