### ISSUE TITLE
(major) issues / bugs in Temporary Files Lock app

### ISSUE THREAD

**Issue by FDVCZ** [nextcloud/files_lock#27]
We have a few issues with the app "**Temporary Files Lock**" (version 0.8.1 on NextCloud 18.0.1).

What this app can do (via web access):
+ (+) prevent renaming of locked file
+ (+) prevent moving of locked file
+ (+) prevent deleting of locked file
+ (+) keep a possibility to copy locked file (however in this case there should be some warning)
+ (+) keep a possibility to add locked file to favorites

Major issues / bugs - what this app currently can not do:
- (-) **Major issue:** **Whole app/lock feature does NOT work correctly with desktop client(!!!)**. For example if someone lock a file, you can delete this file on desktop without any notice/warning. The file will be deleted and even after synchronization remains deleted (you can only find a record in "Activity log" stating "423 Locked" error) and is not restored. And the worst thing is in the moment when this file is unlocked - desktop client even push this "deleting order" to the server and therefore delete file on the server(!!!)
Considering the order for deletion was made in time when file should be protected by the lock feature this is very strange / unwanted / confusing and at this moment practically useless feature.
- (-) When a file is locked, there is only a small lock icon signalizing this state, this can be easily overlooked (compare with W2G app, where the lock is visible very good)
- (-) Locked file can be downloaded without any warning (I would expect something like "Notice: This file is currently locked. Please use this copy for reading only.")
- (-) Locked file can be copied without any warning
- (-) After you add locked file to favorites it disapears a lock icon (appears after reload of the page) and in menu you can even find an option "lock this file" although in a fact the file already is locked).

**Comment by jsuhm** [comment]
Here is my test:
1 - create and lock a text file on a shared folder via the web interface with user A.
2 - map the shared folder on windows explorer via webdav with user B
3 - open the file from windows explorer with user B => it opens without any message
4 - modify and save the file in notepad with user B => a complex webdav error message appears => B can't know who has locked the file
5 - close and re-open the file from windows explorer with user B => modifications made by B are visible => B can believe his modifications are saved to the server
6 - open the file via the web interface with user A => B modifications are not visible
7 - modify and save the file via the web interface with user A
8 - open the file in notepad with user B => modifications made by B at step 4 are not present, modifications made by A are present

This is quite confusing !
I'm agree, it's a major issue.

**Comment by jsuhm** [comment]
any news ?

**Comment by box18box** [comment]
en error or bug? 

[webdav] Fatal: Sabre\DAV\Exception\Locked:  at <<closure>>

0. <<closure>>
   Sabre\DAV\Locks\Plugin->validateTokens("*** sensitive parameters replaced ***")
1. /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
   call_user_func_array([Sabre\DAV\Locks ... "], ["*** sensitive  ... "])
2. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1457
   Sabre\Event\EventEmitter->emit("validateTokens", ["*** sensitive  ... "])
3. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 474
   Sabre\DAV\Server->checkPreconditions("*** sensitive parameter replaced ***", Sabre\HTTP\Response {})
4. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 254
   Sabre\DAV\Server->invokeMethod("*** sensitive parameter replaced ***", Sabre\HTTP\Response {})
5. /var/www/html/apps/dav/lib/Server.php line 319
   Sabre\DAV\Server->exec()
6. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
   OCA\DAV\Server->exec()
7. /var/www/html/remote.php line 165
   require_once("/var/www/html/a ... p")

**Comment by FDVCZ** [comment]
> en error or bug?
> 
> [webdav] Fatal: Sabre\DAV\Exception\Locked: at <>
> 
> 1. <>
>    Sabre\DAV\Locks\Plugin->validateTokens("*** sensitive parameters replaced ***")
> 2. /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
>    call_user_func_array([Sabre\DAV\Locks ... "], ["*** sensitive  ... "])
> 3. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1457
>    Sabre\Event\EventEmitter->emit("validateTokens", ["*** sensitive  ... "])
> 4. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 474
>    Sabre\DAV\Server->checkPreconditions("*** sensitive parameter replaced ***", Sabre\HTTP\Response {})
> 5. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 254
>    Sabre\DAV\Server->invokeMethod("*** sensitive parameter replaced ***", Sabre\HTTP\Response {})
> 6. /var/www/html/apps/dav/lib/Server.php line 319
>    Sabre\DAV\Server->exec()
> 7. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
>    OCA\DAV\Server->exec()
> 8. /var/www/html/remote.php line 165
>    require_once("/var/www/html/a ... p")

What happened here? I suppose this is a result of attempt to delete a file on desktop (sync via desktop client or access via WebDAV) locked by another user(?).
Therefore I suppose this is a correct behaviour (except that user should be noticed about the fact that operation can not be done becasuse the file is locked by other user) - is this explanation correct?.

**Comment by jonasgarstick** [comment]
> We have a few issues with the app "**Temporary Files Lock**" (version 0.8.1 on NextCloud 18.0.1).
> 
> What this app can do (via web access):
> 
> * (+) prevent renaming of locked file
> * (+) prevent moving of locked file
> * (+) prevent deleting of locked file
> * (+) keep a possibility to copy locked file (however in this case there should be some warning)
> * (+) keep a possibility to add locked file to favorites
> 
> Major issues / bugs - what this app currently can not do:
> 
> * (-) **Major issue:** **Whole app/lock feature does NOT work correctly with desktop client(!!!)**. For example if someone lock a file, you can delete this file on desktop without any notice/warning. The file will be deleted and even after synchronization remains deleted (you can only find a record in "Activity log" stating "423 Locked" error) and is not restored. And the worst thing is in the moment when this file is unlocked - desktop client even push this "deleting order" to the server and therefore delete file on the server(!!!)
>   Considering the order for deletion was made in time when file should be protected by the lock feature this is very strange / unwanted / confusing and at this moment practically useless feature.
> * (-) When a file is locked, there is only a small lock icon signalizing this state, this can be easily overlooked (compare with W2G app, where the lock is visible very good)
> * (-) Locked file can be downloaded without any warning (I would expect something like "Notice: This file is currently locked. Please use this copy for reading only.")
> * (-) Locked file can be copied without any warning
> * (-) After you add locked file to favorites it disapears a lock icon (appears after reload of the page) and in menu you can even find an option "lock this file" although in a fact the file already is locked).

Also changes made locally to a locked file, will be pushed by the desktop client to the server after the lock has been released... ouch!

**Comment by k00ni** [comment]
Any news here?

**Comment by FDVCZ** [comment]
k00ni: This is a question for developers of this feature or for users? :-)

**Comment by k00ni** [comment]
> This is a question for developers of this feature or for users? :-)

I use this extension in a paid Nextcloud project successfully. It's sad to see that it has such problems and to some extent frightening. Furthermore, it seems there is no new version planned? I don't want to be too off topic, but I would be interested in plans to solve mentioned problems (especially the first major issue) and possible alternatives, which don't have these problems. Latter maybe via email (in my profile), to not dilute this issue more.

**Comment by solracsf** [comment]
[Desktop Client v3.10](https://github.com/nextcloud/desktop/releases/tag/v3.10.0) should implement all (or a lot of) these features.
To help further develop/debug, please open a separate issue either in this repo or in the Desktop app repo.
Thanks 👍
