### ISSUE TITLE
No Lock file web option on NC 28

### ISSUE THREAD

**Issue by Poneyl** [nextcloud/files_lock#293]
Hi,

I'm upgrading my nextcloud to 28.0.3 from 27.1.3 (offline version) and I installed the 28.0.3 version of Files_lock on it.

I don't see the "file lock" option on the web page. There is something special to do with this version ? On NC 27 everything was fine.

I tried with a fesh online installation dans I get the same result.

Best regards,

![2024-04-16 16_18_37-Applications actives - Apps - Applications - Nextcloud](https://github.com/nextcloud/files_lock/assets/140527362/34e4e205-b09a-4bcf-b3b3-2b55e48627ee)
![2024-04-16 16_18_54-Fichiers - Nextcloud](https://github.com/nextcloud/files_lock/assets/140527362/19f97a7d-3840-4fd1-afbd-3642b61a2ecd)

**Comment by joshtrichards** [comment]
I can't reproduce this issue. It appears for me in v28 just as it does in v27. 

If still not appearing, maybe:

- check your browser console for anything unusual
- post `occ app:list`

**Comment by Poneyl** [comment]
Hi,
I had this error in debug console :

﻿
`/apps/files_lock/js/….mjs?v=afdeffb7-0:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.`

Adding this on my nginx configuration file, solve the problem

`types {
      application/javascript js mjs;
     }
`

I guess there was no .mjs file in the previsous version.

Thx for help.

Regards,

**Comment by Poneyl** [comment]
Hi,
I had this error in debug console :

﻿
`/apps/files_lock/js/….mjs?v=afdeffb7-0:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.`

Adding this on my nginx configuration file, solve the problem

`types {
      application/javascript js mjs;
     }
`

I guess there was no .mjs file in the previsous version.

Thx for help.

Regards,
