### ISSUE TITLE
Add webUI

### ISSUE THREAD

**Issue by rullzer** [nextcloud/files_lock#3]
Using https://github.com/daita/files_lock/issues/2

We should show the locked state and actions in the webui
@juliushaertl

**Comment by jancborchardt** [comment]
Interface-wise, this is what I talked about with Frank and further specified then:
- A "Lock file" entry to the actions menu.
- Clicking it locks it for 30 mins, or you can unlock it yourself too.
- We show an indicator in the list entry about it being locked. I'd say a lock icon somehow overlaid on one corner of the menu icon.
- In the menu it then says in the entry "Unlock" and in a subline: "Locked 16m ago by Frank" so people have context.
- Ideally we have a way for people to then communicate too, e.g. either unlock it or send a message on Talk before. (Could do via modal when you click the "Unlock" entry?)
- Locked files could additionally be shown a bit greyed out, and have " (locked)" attached to their filename so it's extra obvious?

**Comment by juliushaertl** [comment]
I had a quick look and this should all be possible with the existing fileList. @daita Please ping me once https://github.com/daita/files_lock/issues/2 is done as I would then use the existing propfind in the files app to fetch the locking information and display it.

> We show an indicator in the list entry about it being locked. I'd say a lock icon somehow overlaid on one corner of the menu icon.

What do you mean by corner of the menu icon? Maybe you can do a quick mockup?

**Comment by daita** [comment]
Just a reminder, PROPFIND will be not be efficient resource wise. There is no way to have a 'fix/static' parent Id (Id of the folder that contains the file) as during a share, the parent folder can be different from one user to another. Meaning there is no point to store the Id of the current folder when locking a file.

The only efficient way to check which file of a folder is locked or not will be to have the current list of files of a folder, and send a request to my table to check which file from this list is locked.

@rullzer, your point on that one ?

**Comment by daita** [comment]
should be ok, need a way to refresh the display on lock/unlock

**Comment by jancborchardt** [comment]
@juliushaertl this is what the UI could look like, `.icon-password` combined with the menu icon:
![locking ui](https://user-images.githubusercontent.com/925062/69236900-1a8bfa00-0bc7-11ea-8db8-31a99410d0b3.png)

This seems a great first simple version before we overengineer the interface, with all the other info inside the actions menu. Possible further steps:
- Emphasize the lock icon by making it slightly more opaque or full opacity
- Grey out the file name / row entry
- Add a second row below the file name saying "File locked by Roeland Douma" (This is a bit much and duplicates info available in the menu)

What do you think?

**Comment by jancborchardt** [comment]
Alternatively, if that is possible to combine with sharing, we could show the avatar of the person who locked it instead of the sharer, and show the lock icon overlaid there? Then it goes to sharing, and we have the locking info there?

That would be more nicely integrated, but not sure if it’s easy to pull off @juliushaertl?

**Comment by daita** [comment]
Would it be possible to limit the 'Lock File' entry in the ActionMenu to files not to files+folder ?
