### ISSUE TITLE
[PHP] Error: filesize(): stat failed

### ISSUE THREAD

**Issue by andre5tz** [nextcloud/files_lock#34]
Hello,

there seems to be a problem with files_lock. I get a lot of error messages in the nextcloud logging.

`[PHP] Error: filesize(): stat failed for xxx/nextcloud/lib/private/Files/Storage/Local.php#224

PUT /remote.php/dav/files/xxxxxxxxxx/xxxxx.pln.lck
from xx.xxx.xxx.xx by ... at 2020-09-24T22:12:14+02:00`

The problem is already reported in [https://help.nextcloud.com/t/filesize-stat-failed-for/3662](https://help.nextcloud.com/t/filesize-stat-failed-for/3662).

The solution ist reportet in post nr. 11 [https://help.nextcloud.com/t/filesize-stat-failed-for/3662/11](https://help.nextcloud.com/t/filesize-stat-failed-for/3662/11)

When I deactivate the extension, there are no error messages. But I think, this ist not the best solution for files_lock.

Thank you very much for the extension.

Best regards
André

**Comment by Flight777** [comment]
Same here!

**Comment by aleadco** [comment]
Same here!

**Comment by radoeka** [comment]
I've the same issue.  Would be nice if this could be looked into.

The functiontrace is as follows:
[functiontrace.txt](https://github.com/nextcloud/files_lock/files/6274100/functiontrace.txt)

The following files from files_lock are involved:

        "file": "/srv/www/vhosts/owncloud/nextcloud-20.0.8/apps/files_lock/lib/Service/FileService.php",
        "line": 95,
        "function": "get",
        "class": "OC\\Files\\Node\\Folder",

        "file": "/srv/www/vhosts/owncloud/nextcloud-20.0.8/apps/files_lock/lib/Storage/LockWrapper.php",
        "line": 112,
        "function": "getFileFromPath",
        "class": "OCA\\FilesLock\\Service\\FileService",

        "file": "/srv/www/vhosts/owncloud/nextcloud-20.0.8/apps/files_lock/lib/Storage/LockWrapper.php",
        "line": 81,
        "function": "isLocked",
        "class": "OCA\\FilesLock\\Storage\\LockWrapper",

        "file": "/srv/www/vhosts/owncloud/nextcloud-20.0.8/apps/files_lock/lib/Storage/LockWrapper.php",
        "line": 210,
        "function": "checkPermissions",
        "class": "OCA\\FilesLock\\Storage\\LockWrapper",

        "file": "/srv/www/vhosts/owncloud/nextcloud-20.0.8/apps/files_lock/lib/Storage/LockWrapper.php",
        "line": 210,
        "function": "writeStream",
        "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",

**Comment by acsfer** [comment]
Please open a new issue if this is reproductible with NC 22 or 23. Thanks 👍
