### ISSUE TITLE
V30.0.0 is Unavailable in NextCloud App Store

### ISSUE THREAD

**Issue by vagner-dias** [nextcloud/files_lock#352]
Hello,

I am currently using Nextcloud version 29.0.5 and noticed that I cannot find the files_lock app version 30.0.0 in my Nextcloud app store. Could you please confirm if this version is only available for users on NC 30?

**Comment by joshtrichards** [comment]
30.0.0 would only be for Nextcloud Server v30.

https://apps.nextcloud.com/apps/files_lock
