### ISSUE TITLE
Temporary File Lock not working with ONLYOFFICE, Plain Text files.

### ISSUE THREAD

**Issue by tahaun** [nextcloud/files_lock#36]
Other users are allowed to edit ONLYOFFICE and plain .txt. when file is shared and marked locked.

Nextcloud 20.0.5
Ubuntu server 20.04.1
Non-integrated community document server

To recreate,
1. Share a ONLYOFFICE or LibreOffice document (or MS compatible)
2. Lock the file.
3. Log in as another user using incognito (to spoof session)
4. Open shared file and edit.

**Comment by acsfer** [comment]
Should be fixed by https://github.com/ONLYOFFICE/onlyoffice-nextcloud/pull/527
