### ISSUE TITLE
Hide options from UI when file is locked

### ISSUE THREAD

**Issue by thisIsTheFoxe** [nextcloud/files_lock#47]
Hey,
While a file is locked it cannot be renamed or deleted, correct?
So I think it shouldn't even give the option to do so while the file is locked.
Currently a locked file still has "rename" and "delete" options which will not work while the file is locked and show an error as in the screenshot.
I think the same approach should be taken for mobile clients..

Tested with Nextcloud: v23.0.0.9 / sqlite3

<img width="417" alt="Screenshot 2022-01-17 at 14 11 39" src="https://user-images.githubusercontent.com/18512366/149778504-f72f765b-fbb8-4902-a56d-b9e1b7831086.png">

**Comment by juliushaertl** [comment]
Lets track this in https://github.com/nextcloud/files_lock/issues/50
