### ISSUE TITLE
The locktoken supplied does not match any locks on this entity

### ISSUE THREAD

**Issue by dakser** [nextcloud/files_lock#56]
Hi, I have installed the files lock app in Nextcloud, but now I have a lot of errors in the admin/logging, the errors are:

Fatal, Webdav, "Sabre\DAV\Exception\LockTokenMatchesRequestUri: The locktoken supplied does not match any locks on this entity"
Error, PHP, "Error: Undefined offset: 2 at /home/cloudb/public_html/apps/files_lock/lib/Service/FileService.php#126"

Do you know what are causing this and how to solve it? 

I have the last version of files lock app.

Any help is appreciated.

**Comment by juliushaertl** [comment]
Can you paste the full error from the log file? It should contain a trace as well that would provide additional information.

**Comment by dakser** [comment]
Hi Julius, thanks for your answer, the content of the log:

Error, PHP, Error: Undefined offset: 2 at /home/cloudbox/public_html/apps/files_lock/lib/Service/FileService.php#126

{"reqId":"c8O36UZ7o9aQy9IOynXM","level":3,"time":"2022-03-15T19:27:40+00:00","remoteAddr":"177.242.136.122","user":"Coordinacion Almacen","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/Coordinacion%20Almacen/","message":{"Exception":"Error","Message":"Undefined offset: 2 at /home/cloudbox/public_html/apps/files_lock/lib/Service/FileService.php#126","Code":0,"Trace":[{"file":"/home/cloudbox/public_html/apps/files_lock/lib/Service/FileService.php","line":126,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/home/cloudbox/public_html/apps/files_lock/lib/Plugins/FilesLockPlugin.php","line":89,"function":"getFileFromAbsoluteUri","class":"OCA\\FilesLock\\Service\\FileService","type":"->"},{"file":"/home/cloudbox/public_html/3rdparty/sabre/dav/lib/DAV/Locks/Plugin.php","line":148,"function":"getLocks","class":"OCA\\FilesLock\\Plugins\\FilesLockPlugin","type":"->"},{"file":"/home/cloudbox/public_html/3rdparty/sabre/dav/lib/DAV/Locks/Plugin.php","line":98,"function":"getLocks","class":"Sabre\\DAV\\Locks\\Plugin","type":"->"},{"file":"/home/cloudbox/public_html/3rdparty/sabre/dav/lib/DAV/PropFind.php","line":96,"function":"Sabre\\DAV\\Locks\\{closure}","class":"Sabre\\DAV\\Locks\\Plugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/home/cloudbox/public_html/3rdparty/sabre/dav/lib/DAV/Locks/Plugin.php","line":100,"function":"handle","class":"Sabre\\DAV\\PropFind","type":"->"},{"file":"/home/cloudbox/public_html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"propFind","class":"Sabre\\DAV\\Locks\\Plugin","type":"->"},{"file":"/home/cloudbox/public_html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1063,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/cloudbox/public_html/3rdparty/sabre/dav/lib/DAV/Server.php","line":989,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/cloudbox/public_html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1678,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/cloudbox/public_html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1661,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/cloudbox/public_html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":363,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/cloudbox/public_html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/home/cloudbox/public_html/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/cloudbox/public_html/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/cloudbox/public_html/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/cloudbox/public_html/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/cloudbox/public_html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/home/cloudbox/public_html/remote.php","line":167,"args":["/home/cloudbox/public_html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/home/cloudbox/public_html/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mountain Duck/4.1.2.16951 (Windows 10/10.0) (amd64)","version":"20.0.14.2","id":"6230e8e685624"}

Fatal, Webdav, Sabre\DAV\Exception\LockTokenMatchesRequestUri: The locktoken supplied does not match any locks on this entity

{"reqId":"IDEsqfoJgNItKuKz4IDG","level":4,"time":"2022-03-15T19:27:38+00:00","remoteAddr":"177.242.136.122","user":"Coordinacion Almacen","app":"webdav","method":"UNLOCK","url":"/remote.php/dav/files/Coordinacion%20Alm/Alm%20-%20Servicios/2022/F-WH-P01-08%20INSUMOS.xlsx","message":{"Exception":"Sabre\\DAV\\Exception\\LockTokenMatchesRequestUri","Message":"The locktoken supplied does not match any locks on this entity","Code":0,"Trace":[{"file":"/home/cloudbox/public_html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpUnlock","class":"Sabre\\DAV\\Locks\\Plugin","type":"->"},{"file":"/home/cloudbox/public_html/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/cloudbox/public_html/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/cloudbox/public_html/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/cloudbox/public_html/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/cloudbox/public_html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/home/cloudbox/public_html/remote.php","line":167,"args":["/home/cloudbox/public_html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/home/cloudbox/public_html/3rdparty/sabre/dav/lib/DAV/Locks/Plugin.php","Line":297,"CustomMessage":"--"},"userAgent":"Mountain Duck/4.1.2.16951 (Windows 10/10.0) (amd64)","version":"20.0.14.2","id":"6230e8e68565c"}

**Comment by susnux** [comment]
I think this was fixed with NC24 here:
https://github.com/nextcloud/files_lock/commit/9418b4a09d2cbbf3072a04442e8d4bac92da1f0c
